name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'infrastructure'
      - 'automation'
      - 'documentation'
      - 'dependencies'
      - 'ci'
      - 'test'
      - 'codecov'
      - 'testing'
      - 'refactor'
      - 'unit tests'
      - 'release'
  - title: '🏎 Performance'
    labels: 
      - 'performance'
      - 'load'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
      - 'feature'
      - 'enhancement'
  minor:
    labels:
      - 'minor'
      - 'fix'
      - 'bugfix'
      - 'bug'
  patch:
    labels:
      - 'patch'
      - 'infrastructure'
      - 'automation'
      - 'documentation'
      - 'dependencies'
      - 'ci'
      - 'test'
      - 'codecov'
      - 'testing'
      - 'refactor'
      - 'unit tests'
      - 'release'
  default: patch
template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: 'documentation'
    branch:
      - '/docs{0,1}\/.+/'
      - '/documentation\/.+/'
    files:
      - 'README.md'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
      - '^fix.*'
    title:
      - '/fix/i'
      - '/bug/i'
      - '^fix.*'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
  - label: 'maintenance'
    branch:
      - '/maintenance\/.+/'
  - label: 'dependencies'
    branch:
      - '/dependencies\/.+/'