name: Asset Upload

on:
    release:
      types:
        - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.repository }} > Release.txt
      - name: Zip MOD
        run: |
          rm -rf FS25_SiloKing.zip
          zip -r FS25_SiloKing.zip * -x ".git/*" ".github/*" "LICENSE" "README.md" "urls.txt" "*.ps1"
          echo "#### Zip Done ####"
          pwd
          ls -l
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: FS25_SiloKing.zip