name: Asset Upload

on:
  release:
    types:
      - published

jobs:
  build:
    if: github.ref == 'refs/heads/main'  # Ensure the workflow runs only on the main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Zip
        run: |
          repo_name="${{ github.repository }}"
          mod_name="${repo_name#*/}"  # Extract the part after the '/'
          zip_file="${mod_name}.zip"  # Create the dynamic file name
          rm -rf "$zip_file"  # Remove existing zip file if any
          zip -r "$zip_file" * -x ".git/*" ".github/*" "LICENSE" "README.md" "urls.txt" "*.ps1"
          echo "zipfile=$zip_file" >> $GITHUB_ENV  # Export the variable to the environment

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.zipfile }}  # Use the dynamic environment variable