name: Asset Upload

on:
    release:
      types:
        - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Zip
        id: zip_step  # Set an ID for the step to refer to outputs later
        run: |
          repo_name="${{ github.repository }}"
          mod_name="${repo_name#*/}"  # Extract the part after the '/'
          zip_file="${mod_name}.zip"  # Create the dynamic file name
          rm -rf "$zip_file"  # Remove existing zip file if any
          zip -r "$zip_file" * -x ".git/*" ".github/*" "LICENSE" "README.md" "urls.txt" "*.ps1"
          echo "::set-output name=zipfile::$zip_file"  # Set the output for later use

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.zip_step.outputs.zipfile }}  # Use the dynamic output from the previous step