name: Compare XML Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compare-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install required Python libraries
        run: |
          python -m pip install --upgrade pip
          pip install xmltodict deepdiff

      - name: Compare XML Files
        run: |
          cat <<EOF > compare_xml.py
          import os
          import xmltodict
          from deepdiff import DeepDiff

          giants_path = "Giants/data/vehicles"
          sk_pack_path = "SK_Pack/vehicles"
          markdown_file = os.path.join(giants_path, "vehicle.md")

          def read_xml(file_path):
              with open(file_path, "r", encoding="utf-8") as file:
                  return xmltodict.parse(file.read())

          summary = []

          for root, _, files in os.walk(giants_path):
              for file in files:
                  if file.endswith(".xml"):
                      giants_file = os.path.join(root, file)
                      relative_path = os.path.relpath(giants_file, giants_path)
                      sk_pack_file = os.path.join(sk_pack_path, relative_path)

                      if os.path.exists(sk_pack_file):
                          giants_data = read_xml(giants_file)
                          sk_pack_data = read_xml(sk_pack_file)

                          diff = DeepDiff(giants_data, sk_pack_data, ignore_order=True)

                          if diff:
                              summary.append(
                                  f"### Changes in {relative_path}\n```json\n{diff.to_json(indent=2)}\n```\n"
                              )
                      else:
                          summary.append(f"### File missing in SK_Pack\n- {relative_path}\n")

          if not summary:
              output = "# XML Comparison Summary\n\nNo changes detected."
          else:
              output = "# XML Comparison Summary\n\n" + "\n".join(summary)

          with open(markdown_file, "w") as md_file:
              md_file.write(output)
          EOF
          python compare_xml.py

      - name: Upload Summary
        uses: actions/upload-artifact@v4
        with:
          name: xml-comparison-summary
          path: Giants/data/vehicles/vehicle.md
