name: Compare XML Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compare-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install required Python libraries
        run: |
          python -m pip install --upgrade pip
          pip install xmltodict deepdiff

      - name: Compare XML Files
        id: compare
        run: |
          import os
          import xmltodict
          from deepdiff import DeepDiff

          giants_path = "Giants/data/vehicles"
          sk_pack_path = "SK_Pack/vehicles"

          def read_xml(file_path):
              with open(file_path, 'r', encoding='utf-8') as file:
                  return xmltodict.parse(file.read())

          summary = []

          for root, _, files in os.walk(giants_path):
              for file in files:
                  if file.endswith('.xml'):
                      giants_file = os.path.join(root, file)
                      relative_path = os.path.relpath(giants_file, giants_path)
                      sk_pack_file = os.path.join(sk_pack_path, relative_path)

                      if os.path.exists(sk_pack_file):
                          giants_data = read_xml(giants_file)
                          sk_pack_data = read_xml(sk_pack_file)

                          diff = DeepDiff(giants_data, sk_pack_data, ignore_order=True)

                          if diff:
                              summary.append(f"Changes in {relative_path}:\n{diff}\n")
                      else:
                          summary.append(f"File missing in SK_Pack: {relative_path}\n")

          if not summary:
              print("No changes detected.")
          else:
              with open('summary.txt', 'w') as summary_file:
                  summary_file.write("\n".join(summary))

      - name: Upload Summary
        if: steps.compare.outputs.changes != ''
        uses: actions/upload-artifact@v4
        with:
          name: xml-comparison-summary
          path: summary.txt
