name: Update modDesc Version

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(github.ref, 'refs/tags/')
        echo "Latest tag: $latest_tag"
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV

