name: Update modDesc Version

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set latest tag
      id: set-latest-tag
      run: echo "latest_tag=$(git tag | sort --version-sort | tail -n1)" >> $GITHUB_ENV
  
    - name: Tag Docker image as latest
      id: tag-as-latest
      run: |
        echo ${{ github.event.push.tag_name }}